---
title: "Building Skills in Quantitative Biology"
author: "Kim Cuddington, Andrew M. Edwards, Brian Ingalls"
date: "`r format(Sys.time(), '%d %B, %Y')`"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    includes:
      in_header: google_analytics_script.html
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "Building Skills in Quantitative Biology"
---

#  Welcome!

Quantitative skills are essential for biological research. We consider such
skills to include the computational, statistical and mathematical techniques used to study life and
living organisms, including aspects of big data, transparency and reproducibility in science.
However, the breadth of quantitative techniques now employed in biology make it very likely
that there may be no suitable local expertise within a student's home
institution or a biologist's workplace.

This e-book consists of five independent chapters or "modules" designed to teach different quantitative skills to graduate students and biologists working in academia, government agencies and private organisations. A key theme is that while the techniques presented are from various disciplines (such as computer science, statistics and mathematics), they are presented in a way that is suitable for a biological audience. Our examples and approach reflect our personal use of these tools as researchers in biology.

Each module is designed to quickly get you up and running on the topic of interest in 3-5 hours. As such, these materials should be thought of a basic introduction. We provide pointers to more advanced materials, but our aim is to "jump-start" your use of these tools. On the other hand, these modules are not designed for absolute beginners. With the exception of the module on Git and Github, the materials are written assuming that learners have some basic familiarity with R, and a standard undergraduate background in calculus and univariate statistics (see the [Prerequisites section](#prerequisites) for resources to brush up on these materials).

Because the modules are designed to be independent (i.e., you don't have read the whole e-book!), you can select subtopics that are directly relevant to your research. Our hope is that this approach will simultaneously provide more targeted training and reduce the time commitment that would be involved in more generalized formal courses. Pick and choose what you need!

The five modules are:

* **Git and GitHub** (Andrew Edwards) -- covers the tools widely used to share code,
  collaborate with colleagues and create a transparent record of research.

* **R Markdown** (Andrew Edwards) -- demonstrates how to create dynamic documents
  that are fully reproducible, with a clear link between the underlying R code
  and the resulting figures, tables and results.

* **Multivariate analysis** (Kim Cuddington) -- discusses multivariate quantitative
  methods that are used to understand data when there is more than one response (or measurement)

* **Machine learning and classification** (Kim Cuddington) -- continues explorations
  of multivariate data and in particular the topic of classification but using machine learning approaches.

* **Optimization** (Brian Ingalls) -- optimization is the act of identifying the extreme (cheapest,
  tallest, fastest, ...) over a collection of possibilities. Applications include the manipulation  (e.g. optimal
  harvesting or optimal drug dosing) and construction (e.g. robust synthetic genetic circuits) of biological systems, and experimental design.



## Open Science

In the spirit of open science (and using the tools introduced in the first
two modules), this e-book was written collaboratively and
openly in R Markdown, with files shared via GitHub [here](https://github.com/quantitative-biology/Basics){target="_blank"}.

## Feedback

Despite extensive feedback from our student guinea pigs, we anticipate further
revisions based on feedback, since we can consider this work as a living
document. If you use these materials please take some time to
let us know how they work for you, using this
[survey](https://forms.gle/vLkcZq7NxPb2ajTQ6){target="_blank"}.


## About the authors

[Kim Cuddington](https://uwaterloo.ca/biology/people-profiles/kim-md-cuddington){target="_blank"}
is an Associate Professor at the University of Waterloo in the Department
of Biology, with a cross-appointment to Applied Mathematics. She has several projects designed to improve quantitative
education for biology students and has training in instructional design
(University of Waterloo, Center for Teaching Excellence). She teaches courses
that emphasize quantitative methods (such as Quantitative Ecology and
Mathematical Modelling in Biology). Her research involves the use of
mathematics, statistics, and computational approaches to answer questions
regarding population and ecosystem dynamics, invasive species, and impacts of
climate change -- [see www.ecotheory.ca](https://www.ecotheory.ca){target="_blank"}.
Kim has a PhD in biology yet was once told she was too mathematical for a
position in a biology department.

[Andrew Edwards](http://www.chebucto.ns.ca/~english/){target="_blank"} is a
Research Scientist with the Department of Fisheries and Oceans Canada (DFO) at
the Pacific Biological Station in Nanaimo, British Columbia, and holds an Adjunct Professor position in the
Department of Biology at the University of Victoria. He has
previously developed in-person workshops on Git, GitHub and R Markdown (tools
that are widely used in DFO), and co-developed a
quantitative biology course at Dalhousie University. Current work includes
developing methods for fitting size spectra to data, conducting fisheries stock
assessments (including for Pacific Hake, the largest groundfish stock off the
west coast of North America), and recent guidelines to [using mathematical notation
in ecology](https://doi.org/10.1111/2041-210X.13105){target="_blank"}.
Andy has a PhD in applied mathematics yet was once told he was too biological for a position in a math department.

[Brian Ingalls](https://uwaterloo.ca/applied-mathematics/people-profiles/brian-ingalls){target="_blank"}
is an Associate Professor in the Department of Applied Mathematics at the
University of Waterloo, cross-appointed
to the Departments of Biology and Chemical Engineering. He is the author of
Mathematical Modeling in System Biology: An Introduction (2013), and has previously taught
undergraduate and graduate courses on quantitative techniques in biology (including
Computational Modelling of Cellular Systems and Mathematical Cell Biology).
Brian has a PhD in mathematics and everyone has always been too in awe of him
to make remarks about what positions he is qualified for.

## Acknowledgments

We acknowledge support from the Government of Ontario through a grant from
eCampusOntario, and the support of DFO and the Faculty of Science, University of
Waterloo. The grant and the Faculty of Science each funded a student to help
with creating the project. We thank Luwen Chang and Matthew Zhou for their
amazing learning curves, and subsequent help coding up the modules. The
eCampusOntario grant also funded several students to evaluate an early version
of the materials. Lina Aragon Baquero, Lauren Banks, Madison Brook, Jacob
Burbank, Nicole Gauvreau and Aranksha Dilip Thakor provided valuable feedback.

The Git and GitHub module builds upon workshop materials that were originally
developed with Chris Grandin (DFO), who AME also thanks for assistance with the
module.

## Citation

Currently (title may change), please cite this work as:

Cuddington, K, Edwards, A.M., and Ingalls, B. (2021). *Building Skills in Quantitative Biology*. https://www.quantitative-biology.com


## Prerequisites {#prerequisites}

We assume that learners have some basic familiarity with R, and a standard undergraduate background in calculus and univariate statistics. If needed, we have provided some excellent resources below that will help you brush up on these topics. We have tried to choose resources that have a biological bent and will help you get up to speed quickly. In line with the style of this e-book, we have also focused on open source materials. 

### R and RStudio

[R is a programming language]((https://cran.r-project.org/doc/FAQ/R-FAQ.html#What-is-R_003f)) and a free system for statistical computation and graphics . [RStudio](https://www.rstudio.com/) is a piece of software that allows users to more easily work with R. 

The [Software Carpentry](https://software-carpentry.org/) and [Data Carpentry](https://datacarpentry.org/) organizations maintain excellent resources for learning computational tools. There are two sets of modules that users can work through on their own to obtain the needed level of fluency and R to make the most of this e-book. These lessons will teach you how to navigate RStudio, load and clean data, build simple plots, use control flow, and how use the Tidyverse ecosystem of packages. 

- https://datacarpentry.org/R-ecology-lesson/
- https://swcarpentry.github.io/r-novice-gapminder/

Beyond these initial resources, there are a number of useful resources to continue building your R skills. 

- [R for Data Science textbook](https://r4ds.had.co.nz/index.html)
- [RStudio Education](https://education.rstudio.com/learn/beginner/)
- [StackOverflow](https://stackoverflow.com/questions/tagged/r)


### Calculus

A typical biology undergraduate takes a single semester of calculus during their studies. It is difficult for us to recommend specific calculus resources as most will have a lot of material that is not needed specifically for this e-book. We recommend using the following resources to brush up on calculus in general. However, we recommend you focus on building some intuition for derivatives and integration (don't focus too much on memorizing rules and instead focus on the concepts), how to work with simple differential equations, and ideas of optimization.  

- [OpenStax textbook](https://openstax.org/books/calculus-volume-1/pages/1-introduction)
- [KhanAcademy videos and exercises](https://www.khanacademy.org/math)


### Univariate statistics

To prepare for the modules on multivariate analysis, machine learning and classification, and optimization, readers should have a basic understanding of univariate statistics. Similar to calculus, it is more important to understand the key concepts as opposed to memorizing specific formulas or vocabulary. Readers should spend some time reviewing the basic principles of linear regression, hypothesis testing (including the terminology of model parameters, p-values, and confidence intervals), statistical distributions, and the basics of probability theory.

- [OpenStax textbook](https://openstax.org/books/introductory-statistics/pages/1-introduction)
- [Handbook of Biological Statistics](http://biostathandbook.com/)
- [KhanAcademy videos and exercises](https://www.khanacademy.org/math/statistics-probability)
- [Nature series on statistics for biologists](https://www.nature.com/collections/qghhqm/)


